services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env  # Docker inyectará automáticamente las variables de este archivo
    volumes:
      - .:/usr/src/app
    command: npm run dev  # <------ Esto sobreescribe el CMD del Dockerfile
  drupal:
    image: drupal:10-apache
    ports:
      - "8080:80"
    volumes:
      # Guarda tus módulos para que no se borre el 'conector_api'
      - ./drupal-data/modules:/var/www/html/modules/custom
      # MUY IMPORTANTE: Guarda los archivos de configuración y sitios
      - ./drupal-data/sites:/var/www/html/sites
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: db-api-daw
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass1234
    volumes:
      # ESTO ES LO QUE EVITA QUE VUELVA A LA INSTALACIÓN
      - ./drupal-data/db_data:/var/lib/postgresql/data